repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck - Lint shell scripts
        description: Performs linting on bash scripts
        entry: shellcheck
        language: system
        files: ".sh"
    -   id: nbstripout
        name: nbstripout - Strip jupyter notebooks
        description: Stripping Jupyter notebook output (nbstripout)
        entry: nbstripout
        language: system
        files: ".ipynb"
    -   id: isort
        name: isort - Sort Python imports
        description: Formatting Python import order (isort)
        entry: isort
        language: system
        types: [python]
    -   id: black
        name: black - Format Python files
        description: Formatting Python files (black)
        entry: black
        language: system
        types: [python]
