#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Template Title  # The title of the book. Will be placed in the left navbar.
author                      : Author  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

sphinx:
  extra_extensions: [
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
  ]
#  config: 
#   key: value

# repository:
#   url: https://github.com/{your-book-url}
#   path_to_book: path/to/your/book  # An optional path to your book, defaults to repo root
#   branch: yourbranch  # An optional branch, defaults to `master`

html:
  extra_navbar: ""
#   use_repository_button: true
#   use_edit_page_button: true