name: CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci_run:

    runs-on: ubuntu-latest

    steps:

      # actions/checkout@v2 gives access to the repo (https://github.com/actions/checkout)
      - uses: actions/checkout@v2

      # Build the docker container with our custom Dockerfile
      - name: Build Docker container
        run: docker build --file tools/Dockerfile --tag ci_run:${{ github.sha }} .

      # Run the CI checks in the docker container
      # Note: The GITHUB_WORKSPACE volume (repo location) is mounted to /workdir in the container.
      - name: Run Docker container
        run: docker run --volume ${GITHUB_WORKSPACE}:/workdir -t ci_run:${{ github.sha }} bash -c ./tools/ci_run.sh

      # Run vulnerability checks on the Docker container
      # - uses: Azure/container-scan@v0
      #   with:
      #     image-name: ci_run:${{ github.sha }}
